{
 "title": "Jitsi Meet",
 "description": "Dashboard for stats gathered by 3rd party exporter karrieretutor/jitsi-prom-exporter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(go_info{job = \"jitsi-exporter\"}, instance)"
   },
   {
    "name": "containers",
    "label": "Containers",
    "query": "label_values(docker_container_running_state{instance =~ \"$instances\"}, name)"
   },
   {
    "name": "instances",
    "label": "Instances",
    "query": "label_values(docker_container_running_state, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Jitsi / OS / Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - docker_container_start_time_seconds{instance =~ \"$instances\", name =~ \"e_jvb_1\"}"
    }
   ]
  },
  {
   "title": "Video Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "endpoints_sending_video{instance = \"$instance\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Failed Conferences",
   "type": "singlestat",
   "description": "The total number of failed conferences on the bridge. A conference is marked as failed when all of its channels have failed. A channel is marked as failed if it had no payload activity",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "total_failed_conferences{instance = \"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "Largest Conference",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "largest_conference{instance = \"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "Total created Conferences",
   "type": "singlestat",
   "description": "Nombre total de conférences créé depuis le démarrage du service",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "total_conferences_created{instance = \"$instance\"}",
     "legendFormat": "total_conferences_created"
    }
   ]
  },
  {
   "title": "RX Bytes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "bytes",
   "valueName": "delta",
   "targets": [
    {
     "expr": "total_bytes_received{instance = \"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "Video Users Mean",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "endpoints_sending_video{instance = \"$instance\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Conferences Mean",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "targets": [
    {
     "expr": "conferences{instance = \"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "Conferences",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "conferences{instance = \"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "Participants",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 2 },
   "targets": [
    {
     "expr": "participants{instance = \"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "Audio Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "targets": [
    {
     "expr": "endpoints_sending_audio{instance = \"$instance\"}"
    }
   ]
  },
  {
   "title": "Partially Failed Conferences",
   "type": "singlestat",
   "description": "The total number of partially failed conferences on the bridge. A conference is marked as partially failed when some of its channels has failed. A channel is marked as failed if it had no payload activity.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "format": "short",
   "valueName": "delta",
   "targets": [
    {
     "expr": "total_partially_failed_conferences{instance = \"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "Total Conference Duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "format": "s",
   "valueName": "delta",
   "targets": [
    {
     "expr": "total_conference_seconds{instance = \"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "Total Participants",
   "type": "singlestat",
   "description": "Nombre total de participants depuis le démarrage du service",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "total_participants{instance = \"$instance\"}",
     "legendFormat": "total_participants"
    }
   ]
  },
  {
   "title": "TX Bytes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "format": "bytes",
   "valueName": "delta",
   "targets": [
    {
     "expr": "total_bytes_sent{instance = \"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "Audio Users Mean",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "targets": [
    {
     "expr": "endpoints_sending_audio{instance = \"$instance\"}"
    }
   ]
  },
  {
   "title": "Participants Mean",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "targets": [
    {
     "expr": "participants{instance = \"$instance\"}",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total[1m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)",
     "legendFormat": "Used Memory"
    },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free Memory" },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "Buffer Memory" },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "Cached Memory" }
   ]
  },
  {
   "title": "Load 1m",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "load 1m" },
    { "expr": "node_load5", "legendFormat": "load 5m" },
    { "expr": "node_load15", "legendFormat": "load 15m" }
   ]
  },
  {
   "title": "Used  Space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/etc/hosts\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/etc/hosts\"})"
    },
    {}
   ]
  },
  {
   "title": "I/0  Wait Mean",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 12 },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"nodeexporter:9100\"}[30m])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Container CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image!=\"\",container_label_org_label_schema_group=\"\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"})) * 100",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Containers Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image!=\"\",container_label_org_label_schema_group=\"\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Conferences",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "conferences{instance = \"$instance\"}",
       "legendFormat": "Threads"
      }
     ]
    },
    {
     "title": "Participants",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "participants{instance = \"$instance\"}",
       "legendFormat": "people"
      }
     ]
    },
    {
     "title": "Video streams",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "videostreams{instance = \"$instance\"}",
       "legendFormat": "Threads"
      }
     ]
    },
    {
     "title": "Channels created",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(total_channels{instance = \"$instance\"}[1h])",
       "legendFormat": "channels"
      }
     ]
    },
    {
     "title": "Audio channels",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "endpoints_sending_audio{instance = \"$instance\"}",
       "legendFormat": "Threads"
      }
     ]
    },
    {
     "title": "Video channels",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "endpoints_sending_video{instance = \"$instance\"}",
       "legendFormat": "Threads"
      }
     ]
    },
    {
     "title": "Jitter aggregate",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "jitter_aggregate{instance = \"$instance\"}",
       "legendFormat": "Jitter"
      }
     ]
    },
    {
     "title": "Datachannel messages received",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(total_data_channel_messages_received{instance = \"$instance\"}[5m])",
       "legendFormat": "msg"
      }
     ]
    },
    {
     "title": "Bitrate upload",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "Kbits" }
     ],
     "targets": [
      {
       "expr": "bit_rate_upload{instance = \"$instance\"}",
       "legendFormat": "rate"
      }
     ]
    },
    {
     "title": "Packet rate upload",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "packet_rate_upload{instance = \"$instance\"}",
       "legendFormat": "Packets"
      }
     ]
    },
    {
     "title": "RTT aggregate",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rtt_aggregate{instance = \"$instance\"}",
       "legendFormat": "RTT"
      }
     ]
    },
    {
     "title": "Datachannel messages sent",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(total_data_channel_messages_sent{instance = \"$instance\"}[5m])",
       "legendFormat": "msg"
      }
     ]
    },
    {
     "title": "Bitrate download",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "Kbits" }
     ],
     "targets": [
      {
       "expr": "bit_rate_download{instance = \"$instance\"}",
       "legendFormat": "rate"
      }
     ]
    },
    {
     "title": "Packet rate download",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "packet_rate_download{instance = \"$instance\"}",
       "legendFormat": "Packets"
      }
     ]
    },
    {
     "title": "Loss rate upload",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "loss_rate_upload{instance = \"$instance\"}",
       "legendFormat": "Loss"
      }
     ]
    },
    {
     "title": "Loss-limited participant seconds",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(total_loss_limited_participant_seconds{instance = \"$instance\"}[5m])",
       "legendFormat": "time"
      }
     ]
    },
    {
     "title": "Bytes sent",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(total_bytes_sent{instance = \"$instance\"}[1h])",
       "legendFormat": "rate"
      }
     ]
    },
    {
     "title": "Bytes received",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 42 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(total_bytes_received{instance = \"$instance\"}[1h])",
       "legendFormat": "rate"
      }
     ]
    },
    {
     "title": "Loss-controlled participant seconds",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 42 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(total_loss_controlled_participant_seconds{instance = \"$instance\"}[5m])",
       "legendFormat": "time"
      }
     ]
    },
    {
     "title": "Loss rate download",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "loss_rate_download{instance = \"$instance\"}",
       "legendFormat": "Loss"
      }
     ]
    },
    {
     "title": "Loss-degraded participant seconds",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(total_loss_degraded_participant_seconds{instance = \"$instance\"}[5m])",
       "legendFormat": "time"
      }
     ]
    },
    {
     "title": "Conference sizes combined",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "sum by (le) (conference_sizes_combined_bucket{job = \"jitsi\"})",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hidden",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Conference sizes",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 16, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "sum by (le) (conference_sizes_bucket{job = \"jitsi\"})",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Exporter CPU usage",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{instance = \"$instance\"}[5m])",
       "legendFormat": "{{ CPU }}"
      }
     ]
    },
    {
     "title": "No transport channels",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 19 },
     "format": "short",
     "valueName": "delta",
     "targets": [
      {
       "expr": "total_no_transport_channels{instance = \"$instance\"}",
       "legendFormat": "{{ CPU }}"
      }
     ]
    },
    {
     "title": "No payload channels",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 21 },
     "format": "short",
     "valueName": "delta",
     "targets": [
      {
       "expr": "total_no_payload_channels{instance = \"$instance\"}",
       "legendFormat": "{{ CPU }}"
      }
     ]
    },
    {
     "title": "Total Channels",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 23 },
     "format": "short",
     "valueName": "delta",
     "targets": [
      {
       "expr": "total_channels{instance = \"$instance\"}",
       "legendFormat": "{{ CPU }}"
      }
     ]
    }
   ]
  }
 ]
}